services:
  # 1. Database PostgreSQL
  postgres-db: 
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: database_barcode  
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: a           
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. Backend (Python + FastAPI)
  backend-app:
    build: ./backend
    container_name: backend_container
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres-db
    environment:
      - ENV=development
      - DB_HOST=postgres-db
      - DB_NAME=database_barcode
      - DB_USER=postgres
      - DB_PASS=a
      - DB_PORT=5432

  # 3. Frontend (React + Vite)
  frontend-app:
    build: ./frontend
    container_name: frontend_container
    restart: unless-stopped
    ports:
      - "3001:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-app
    environment:
      - VITE_API_URL=http://localhost:8000

#machine data
  machine-data:
    build: ./machine_data
    container_name: machine_data_container
    restart: always
    depends_on:
      - postgres-db
    environment:
      - MQTT_BROKER=192.168.1.205
      - MQTT_PORT=1883
      - DB_NAME=database_barcode
      - DB_USER=postgres
      - DB_PASS=a
      - DB_HOST=postgres-db
      - DB_PORT=5432

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      app_net:
        ipv4_address: 192.168.1.205

volumes:
  pg_data:

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24